sudo: false
language: node_js
node_js:
    - '10'
branches:
    only:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install -g codecov
    - npm install coveralls
    - npm install
script:
    - npm test
    - codecov
    - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
